fail_fast: true
repos:
  - repo: https://github.com/ambv/black
    rev: 'master'
    hooks:
      - id: black
        args: [--diff, --check]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'master'
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'master'
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--ignore-missing-imports]
